### ISSUE TITLE
[Feature Request] Ability to blacklist dimensions from being decorated

### ISSUE THREAD

**Issue by darkphan** [Melonslise/Subterranean-Wilderness#7] opened 2020-10-26 01:21 UTC
Would be nice if we could add in the ability to blacklist certain dimensions from being decorated by the mod? (Or add in support for The Undergarden :D)

**Comment by Melonslise** [comment] 2020-12-30 17:36
Duplicate of #4

**Closed** 2021-01-11 22:29 UTC
Labels: enhancement
