### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by harmalom** [Melonslise/Subterranean-Wilderness#33] opened 2021-03-23 18:02 UTC
The OptiFine people say it is your error, but I don't know, but I leave some images for reference. 
![2021-03-20_13 30 23](https://user-images.githubusercontent.com/67077986/112195452-fafc4b80-8bd7-11eb-9afa-7b672dcb8375.png)
![2021-03-20_13 30 32](https://user-images.githubusercontent.com/67077986/112195464-fdf73c00-8bd7-11eb-8d23-6030baa2c9a6.png)
![2021-03-20_13 31 03](https://user-images.githubusercontent.com/67077986/112195474-00599600-8bd8-11eb-95f8-99296ad0c32a.png)

**Comment by PaintNinja** [comment] 2021-03-24 14:31
Duplicate of #32, use Optifine G7 in the meantime instead of G8+ until the update with the fix comes out.

**Closed by PaintNinja** 2021-03-24 14:31 UTC
Labels: duplicate
