### ISSUE TITLE
Add option to disable foxfire mushroom generation in config

### ISSUE THREAD

**Issue by ninovd1** [Melonslise/Subterranean-Wilderness#55] opened 2021-08-18 14:42 UTC
Hello Melonslise!

There is no option to disable foxfire mushroom generation.
Could you please add this into the config? I would really appreciate that!

Thank you for reading this :)
Sincerely, ninovd1

**Comment by PaintNinja** [comment] 2021-08-21 13:05
Duplicate of #44

**Closed by PaintNinja** 2021-08-21 13:05 UTC
Labels: duplicate, enhancement
